### PR TITLE
re-add query.sql for movies example

### PR DESCRIPTION
**Pull request by bollwyvl**
Looks like `.gitignore` prevented `query.sql` from ever getting added, as it doesn't show up with

```
git log -- examples/movies/query.sql
```

This re-adds it with `git add -f`, but maybe there's something more to do (remove `*.sql` from `.gitignore?`) 

Is it worth adding tests to actually try running the examples?

### CODE REVIEW

**Comment by mmarchetti** [comment]
+1 users following the tutorial doc are hitting this problem. 

I support the idea of running the kapsels as part of testing, but propose that be in a separate PR.

**Comment by mmarchetti** [comment]
@bollwyvl, @havocp Are we ok to merge this? This is biting people who try to run the walkthrough.

**Comment by havocp** [comment]
May want to go ahead and fix .gitignore or we're asking for trouble (will we ignore this file's changes if someone changes it?). There's a way to un-ignore only this particular .sql file I believe, check out the git docs... or if we have no other sql files, remove *.sql seems ok ...

**Comment by bollwyvl** [comment]
Fixed up gitignore! Will merge if/when tests pass!

**Comment by mmarchetti** [comment]
👍

**Comment by bollwyvl** [comment]
Ha, can't merge. @havocp, anything else you need to see here?

**Comment by havocp** [comment]
lgtm!

**Comment by mmarchetti** [comment]
@havocp, I think you're the only one with write perms here, can you click the big green button for us?

**Comment by havocp** [comment]
Oops, didn't even notice which repo this was on :-)

**Pull request merged**
